M48
; DRILL file {KiCad 9.0.2} date 2025-07-10T22:39:00-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-10T22:39:00-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X109.5Y-139.25
X118.5Y-139.25
T2
X38.0Y-156.0
X38.5Y-72.0
X122.5Y-71.5
X122.5Y-156.0
M30
